### ISSUE TITLE
esng.say() does nothing

### ISSUE THREAD

**Issue by vinipsmaker** [gooofy/py-espeak-ng#2]
How do I debug what's the error? Function just return and nothing is done.

**Comment by vinipsmaker** [comment]
Fixed the issue by setting `esng.voice` to `en-us` before running. Shouldn't the function raise an error if voice is not found? The `g2p` function raise an issue, but `say` doesn't.

**Comment by gooofy** [comment]
ok, I have just commit a test + fix for this, say() will return the message(s) espeak-ng produces.
