### ISSUE TITLE
Please distribute tests and license on pypi archive

### ISSUE THREAD

**Issue by scarabeusiv** [gooofy/py-espeak-ng#3]
Pypi package does not contain license which is bit required by the apache license.

Also if you could distribute tests we could validate version shipped in distributions (in this case openSUSE) because otherwise we have no easy way how to do sanity checking of python packages.

Simple MANIFEST.in file should do the trick.

**Comment by gooofy** [comment]
0.1.8 should include readme, tests and license

thanks for the hint! :)
