### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by kushagra98** [gooofy/py-espeak-ng#5]
I don't know how to get rid of this issue. I'm using Ubuntu. 
![Error](https://user-images.githubusercontent.com/41884747/56585523-9efba780-65fb-11e9-8ff6-8b510b2e472e.png)
Nothing happens with passing the value of shell=True in subprocess call as suggested by the web.

**Comment by gooofy** [comment]
Do you have espeak-ng installed? try running

```
[guenter@dagobert tmp]$ espeak-ng --version
eSpeak NG text-to-speech: 1.49.1  Data at: /usr/share/espeak-ng-data
```

from a terminal

**Comment by kushagra98** [comment]
it requires "espeak-ng-espeak" and "espeak" as well. Now it works. Thanks :)

**Comment by Tetsujinfr** [comment]
> it requires "espeak-ng-espeak" and "espeak" as well. Now it works. Thanks :)

hi
can you please elaborate a bit more on how you fixed this issue please?
thanks a lot

**Comment by Tetsujinfr** [comment]
ok, so that worked after installing espeak-ng with:
`sudo apt-get install espeak-ng`

Kind of 101 here but since I was not familiar with espeak, not with espek-ng, I wanted to share. Thanks for leading me to a fix of the error.
